// 📦 استيراد المكتبات الضرورية
import jsPDF from 'jspdf';
import 'jspdf-autotable';

// 🧠 دالة تصدير التقرير إلى PDF
export const exportRefugeesReportToPDF = async (data) => {
  try {
    if (!data || data.length === 0) {
      alert('لا توجد بيانات لتصديرها إلى PDF');
      return;
    }

    // 🔹 إنشاء مستند PDF بوضع أفقي (Landscape)
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'pt',
      format: 'A4',
    });

    // 🏷️ إعداد الترويسة (Header)
    const title = 'Refugees Detailed Report';
    const generatedDate = new Date().toLocaleString();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(title, 40, 40);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${generatedDate}`, 40, 60);

    // 🧾 استخراج الأعمدة (keys من أول صف)
    const columns = Object.keys(data[0]);

    // 🧱 تحويل البيانات إلى صفوف ثنائية الأبعاد
    const rows = data.map((row) => columns.map((col) => (row[col] !== null ? String(row[col]) : '')));

    // 📊 رسم الجدول
    doc.autoTable({
      startY: 80,
      head: [columns],
      body: rows,
      styles: {
        fontSize: 8,
        cellPadding: 4,
        overflow: 'linebreak',
        lineColor: [200, 200, 200],
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: [22, 160, 133],
        textColor: 255,
        fontStyle: 'bold',
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      margin: { top: 80, left: 40, right: 40, bottom: 60 },
      didDrawPage: (data) => {
        // ✅ ذيل الصفحة (Footer)
        const pageCount = doc.internal.getNumberOfPages();
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(`Page ${pageCount}`, doc.internal.pageSize.getWidth() - 70, doc.internal.pageSize.getHeight() - 30);
        doc.text('Generated by Refugee Management System', 40, doc.internal.pageSize.getHeight() - 30);
      },
    });

    // 💾 حفظ التقرير
    doc.save(`Refugees_Report_${Date.now()}.pdf`);
  } catch (error) {
    console.error('❌ خطأ أثناء تصدير التقرير:', error);
    alert('حدث خطأ أثناء توليد ملف PDF');
  }
};
